In [29]:
import numpy as np

# 활성화함수->sigmoid
def actf(x):
    return 1/(1+np.exp(-x))

# 시그모이드 함수의 미분치
def actf_deriv(x):
    return x*(1-x)

# 입력노드의 개수, 은닉노드의 개수, 출력노드의 개수
inputs,hiddens,outputs=2,2,1
learning_rate=0.2

# 훈련 샘플과 정답 (XNOR게이트: 같으면 1, 다르면 0)
X=np.array([[0,0],[0,1],[1,0],[1,1]])
T=np.array([[1],[0],[0],[1]])

# 가중치와 바이어스 
W1=np.array([[0.10,0.20],[0.30,0.40]])
W2=np.array([[0.50],[0.60]])
B1=np.array([0.1,0.2])
B2=np.array([0.3])

# 순방향 전파 계산
def predict(x):
    layer0=x # 입력을 layer0에 대입한다.
    Z1=np.dot(layer0,W1)+B1 # 행렬의 곱을 계산한다.
    layer1=actf(Z1) # 활성화 함수를 적용한다.
    Z2=np.dot(layer1,W2)+B2 # 행렬의 곱을 계산한다.
    layer2=actf(Z2) # 활성화 함수를 적용한다.
    return layer0,layer1,layer2

# 순방향 패스 test 
def test():
    for x,y in zip(X,T):
        x=np.reshape(x,(1,-1)) # x를 2차원 행렬로 만든다. 입력은 2차원이어야 한다. 
        layer0,layer1,layer2=predict(x)
        print(x,y,layer2,'\n')
test()

[[0 0]] [1] [[0.70938314]] 

[[0 1]] [0] [[0.72844306]] 

[[1 0]] [0] [[0.71791234]] 

[[1 1]] [1] [[0.73598705]] 



In [37]:
# 역방향 전파 계산
def fit():
    global W1,W2,B1,B2 # 전역 변수를 변경하기 위해 global키워드를 사용한다. 
    for i in range(90000): # 9만번 반복
        for x,y in zip(X,T):# 학습 샘플을 하나씩 꺼낸다. 
            x=np.reshape(x,(1,-1)) # 2차원 행렬로 만든다.
            y=np.reshape(y,(1,-1)) # 2차원 행렬로 만든다.
            
            layer0,layer1,layer2=predict(x) # 순방향 계산
            layer2_error = layer2-y # 출력층의 오차 계산
            layer2_delta = layer2_error*actf_deriv(layer2) # 출력층의 델타 계산
            layer1_error = np.dot(layer2_delta,W2.T) # 은닉층의 오차 계산
            layer1_delta = layer1_error*actf_deriv(layer1) # 은닉층의 델타 계산
            
            W2 += -learning_rate*np.dot(layer1.T,layer2_delta)
            W1 += -learning_rate*np.dot(layer0.T,layer1_delta)
            B2 += -learning_rate*np.sum(layer2_delta,axis=0)
            B1 += -learning_rate*np.sum(layer1_delta,axis=0)

# 역전파 테스트
def test2():
    for x,y in zip(X,T):
        x=np.reshape(x,(1,-1)) # x를 2차원 행렬로 만든다. 입력은 2차원이어야 한다. 
        layer0,layer1,layer2=predict(x)
        print(x,y,layer2,'\n')
fit()
test2()

[[0 0]] [1] [[0.99448388]] 

[[0 1]] [0] [[0.00569874]] 

[[1 0]] [0] [[0.00570093]] 

[[1 1]] [1] [[0.99302702]] 

